### ISSUE TITLE
Bulk updates might break packages' requirements.

### ISSUE THREAD

**Issue by hyp3rd** [robertdebock/ansible-role-update_pip_packages#1]
## Preserve the integrity of the python environment

Upgrading in bulk a list of python packages may, and most certainly will, break several requirements (version mismatches etc.)

## Integrity check

Producing reports and integrity checks (a simple `pip check`) to get the health status of the environment pre and post-installation might help.

Also, try to provide a way to feed the role with a dictionary of packages you are willing to update, with the related version expected.

**Comment by robertdebock** [comment]
Will have a look, thanks @hyp3rd for the feedback!

**Comment by robertdebock** [comment]
Should be fixed now, Thanks F!
